inputs:

{
  config,
  lib,
  pkgs,
  ...
}:

let
  inherit (lib)
    mkOption
    types
    mkIf
    mkDefault
    ;
  cfg = config.programs.illogical-impulse;

  # Use dotfiles from flake input
  dotfilesSource = inputs.dotfiles;

  # Custom packages
  customPkgs = import ../pkgs { inherit pkgs; };
  gruvboxIconsPath = "${customPkgs.gruvbox-plus-icons}/share/icons";
in
{
  options.programs.illogical-impulse.hyprland = {
    plugins = mkOption {
      type = types.listOf types.package;
      default = [ ];
      description = "List of Hyprland plugins to install and load";
    };
  };

  config = mkIf cfg.enable {
    # Fake venv for QuickShell scripts to use the Nix python environment
    home.file = {
      ".local/state/quickshell/.venv/bin/activate".text = ''
        # Generated by Illogical Impulse Flake
        export VIRTUAL_ENV="${config.programs.illogical-impulse.internal.pythonEnv}"
        export PATH="${config.programs.illogical-impulse.internal.pythonEnv}/bin:$PATH"
        deactivate () {
            # Dummy function for compatibility
            return 0
        }
      '';
      ".local/state/quickshell/.venv/bin/python".source =
        "${config.programs.illogical-impulse.internal.pythonEnv}/bin/python";
      ".local/state/quickshell/.venv/bin/python3".source =
        "${config.programs.illogical-impulse.internal.pythonEnv}/bin/python3";
      ".local/state/quickshell/.venv/pyvenv.cfg".text = ''
        home = ${config.programs.illogical-impulse.internal.pythonEnv}/bin
        include-system-site-packages = false
        version = 3.11.0
      '';
    };

    # Install the plugins to the user environment so they are available
    home.packages = cfg.hyprland.plugins;

    # Configure icon theme for GTK and Qt applications
    gtk = {
      enable = mkDefault true;
      iconTheme = {
        name = mkDefault "Gruvbox-Plus-Dark";
        package = mkDefault customPkgs.gruvbox-plus-icons;
      };
    };

    # Set icon theme via dconf for GNOME/GTK apps
    dconf.settings = {
      "org/gnome/desktop/interface" = {
        icon-theme = mkDefault "Gruvbox-Plus-Dark";
      };
    };

    # Dotfiles management via Home Manager (XDG Config)
    xdg.configFile = {
      "chrome-flags.conf".source = "${dotfilesSource}/dots/.config/chrome-flags.conf";
      "code-flags.conf".source = "${dotfilesSource}/dots/.config/code-flags.conf";
      "darklyrc".source = "${dotfilesSource}/dots/.config/darklyrc";
      "fuzzel".source = "${dotfilesSource}/dots/.config/fuzzel";
      "kde-material-you-colors".source = "${dotfilesSource}/dots/.config/kde-material-you-colors";
      "Kvantum".source = "${dotfilesSource}/dots/.config/Kvantum";
      "matugen".source = "${dotfilesSource}/dots/.config/matugen";
      "mpv".source = "${dotfilesSource}/dots/.config/mpv";

      "thorium-flags.conf".source = "${dotfilesSource}/dots/.config/thorium-flags.conf";
      "wlogout".source = "${dotfilesSource}/dots/.config/wlogout";
      "xdg-desktop-portal".source = "${dotfilesSource}/dots/.config/xdg-desktop-portal";

      # Patch QuickShell scripts to fix shebangs (e.g., #!/bin/bash -> #!/nix/store/.../bash)
      "quickshell".source =
        pkgs.runCommand "quickshell-patched"
          {
            buildInputs = [
              pkgs.bash
              config.programs.illogical-impulse.internal.pythonEnv
            ];
          }
          ''
            cp -r ${dotfilesSource}/dots/.config/quickshell $out
            chmod -R +w $out

            # Replace complex shebangs that patchShebangs can't handle with standard python
            # The complex shebang tried to source a venv, but we provide pythonEnv directly via Nix
            find $out -name "*.py" -print0 | xargs -0 sed -i 's|^#!.*ILLOGICAL_IMPULSE_VIRTUAL_ENV.*|#!/usr/bin/env python3|'

            # Suppress permission errors when writing to /dev/pts in applycolor.sh
            sed -i 's|/dev/pts/\*|/dev/pts/* 2>/dev/null|' $out/ii/scripts/colors/applycolor.sh

            patchShebangs $out
          '';

      # Fontconfig wrapper to ensure system fonts are loaded
      "fontconfig/fonts.conf".text = ''
        <?xml version="1.0"?>
        <!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">
        <fontconfig>
            <include ignore_missing="yes">/etc/fonts/fonts.conf</include>
            <match target="font">
                <edit name="rgba" mode="assign">
                <const>none</const>
            </edit>
          </match>
        </fontconfig>
      '';
    };

    # Dotfiles management via Home Manager (XDG Data)
    xdg.dataFile = {
      # Note: Icons are installed via packages (gruvbox-plus-icons)
      # and the custom icon is handled here if needed, but it's usually in the package too?
      # Re-adding the single SVG manually just in case
      "icons/hicolor/scalable/apps/illogical-impulse.svg".source =
        "${dotfilesSource}/dots/.local/share/icons/illogical-impulse.svg";
    };

    # Use activation script ONLY for stateful integration
    home.activation.copyIllogicalImpulseConfigs = config.lib.dag.entryAfter [ "writeBoundary" ] ''
      # Path to the config directory in the dotfiles source
      configPath="${dotfilesSource}/dots/.config"
      targetPath="$HOME/.config"

      # Create illogical-impulse directory structure if it doesn't exist (Stateful config)
      $DRY_RUN_CMD mkdir -p "$targetPath/illogical-impulse"

      # Copy the default config.json only if it doesn't already exist
      if [ ! -f "$targetPath/illogical-impulse/config.json" ]; then
        if [ -f "$configPath/illogical-impulse/config.json" ]; then
          $DRY_RUN_CMD cp "$configPath/illogical-impulse/config.json" "$targetPath/illogical-impulse/config.json"
          $DRY_RUN_CMD chmod u+w "$targetPath/illogical-impulse/config.json"
        fi
      fi

      # Handle kdeglobals (Mutable copy)
      # If it's a symlink (likely from previous HM generation), remove it first
      if [ -L "$targetPath/kdeglobals" ]; then
          $DRY_RUN_CMD rm "$targetPath/kdeglobals"
      fi

      # We copy it if it doesn't exist (or was just removed), to allow scripts to modify it
      if [ ! -f "$targetPath/kdeglobals" ]; then
         if [ -f "$configPath/kdeglobals" ]; then
             $DRY_RUN_CMD cp "$configPath/kdeglobals" "$targetPath/kdeglobals"
             $DRY_RUN_CMD chmod u+w "$targetPath/kdeglobals"
         fi
      else
         # Ensure it's writable even if it exists
         $DRY_RUN_CMD chmod u+w "$targetPath/kdeglobals"
      fi

      # Handle konsole directory (Mutable directory with managed files)
      konsoleTarget="$HOME/.local/share/konsole"
      konsoleSource="${dotfilesSource}/dots/.local/share/konsole"

      # If it is a symlink (from previous HM generation), remove it
      if [ -L "$konsoleTarget" ]; then
          $DRY_RUN_CMD rm "$konsoleTarget"
      fi

      # Ensure directory exists
      if [ ! -d "$konsoleTarget" ]; then
          $DRY_RUN_CMD mkdir -p "$konsoleTarget"
      fi

      # Sync files (copy managed files into the mutable directory and make writable)
      for file in "$konsoleSource"/*; do
          filename=$(basename "$file")
          # Copy (force overwrite) instead of symlink so the file itself is mutable
          # Use rm first to avoid "same file" errors if it was a hardlink or symlink previously
          if [ -e "$konsoleTarget/$filename" ]; then
              $DRY_RUN_CMD rm -f "$konsoleTarget/$filename"
          fi
          $DRY_RUN_CMD cp "$file" "$konsoleTarget/$filename"
          $DRY_RUN_CMD chmod u+w "$konsoleTarget/$filename"
      done

      # Fix Qt icon theme configuration to use Gruvbox-Plus-Dark/Gruvbox-Plus-Light with Papirus fallback
      # This is still needed because qt6ct might be generating its config
      for qt_conf in "$targetPath/qt5ct/qt5ct.conf" "$targetPath/qt6ct/qt6ct.conf"; do
        if [ -f "$qt_conf" ]; then
          $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI$/icon_theme=Gruvbox-Plus-Dark/' "$qt_conf"
          $DRY_RUN_CMD sed -i 's/^icon_theme=OneUI-light$/icon_theme=Gruvbox-Plus-Light/' "$qt_conf"
        fi
      done

      # Change icon theme in kde-material-you-colors config
      $DRY_RUN_CMD sed -i 's/iconsdark = breeze-plus/iconslight=Gruvbox-Plus-Dark/' "$targetPath/kde-material-you-colors/config.conf"
      $DRY_RUN_CMD sed -i 's/iconslight = breeze-plus/iconslight=Gruvbox-Plus-Light/' "$targetPath/kde-material-you-colors/config.conf"
    '';
  };
}
